### ISSUE TITLE
Add support for Vault Id

### ISSUE THREAD

**Issue by claussa** [sadv1r/ansible-vault-editor-idea-plugin#38]
Ansible Vault offers the possibility with 1.2 version to specify the vault-id-label.
With vault-id-label, it is also possible to store password for the specify vault-id-label and so decrypt vault if the vault-id-label's password is store

I am very hype by your plugin and I can implements this feature.

**Comment by sadv1r** [comment]
Hi! Plugin now stores password for the vault by file path. It’s a good idea to store it by vault-id if it exists. I think this is must have feature here and you can implement it if you want. I can help, if you need

**Comment by aelexor** [comment]
@claussa 
Let's implement, we really do not have enough it

**Comment by artheus** [comment]
@claussa the plugin will not work if there is a vault-id specified in the Vault file header. Therefore I consider this a defect. And would file this issue as a bug rather than an enhancement

**Comment by sadv1r** [comment]
@artheus you're absolutely right!

**Comment by sadv1r** [comment]
Currently [there is a bug](https://github.com/ansible/ansible/issues/72261), that blocks this plugin to support vault id, but I'm trying to find a workaround

**Comment by sadv1r** [comment]
Ansible maintainer helped with the issue, so Vault Id support added in #53

**Comment by sadv1r** [comment]
@claussa @aelexor @artheus guys, I don't have a place where I really using vault id labels, that's why I can't fully check my implementation.
I uploaded eap version of a plugin with this functionality and it will be really cool if you can check it on your use cases, thanks!
Eap version can be downloaded here: https://plugins.jetbrains.com/plugin/14278-ansible-vault-editor/versions/eap/102495
You can install it as a file, [or enable eap versions for repository in IDE](https://plugins.jetbrains.com/docs/marketplace/custom-release-channels.html#configuring-a-custom-channel-in-intellij-platform-based-ides)

**Comment by aelexor** [comment]
@sadv1r Hi!
I checked it and it is working!
<img width="1017" alt="Screenshot 2020-11-19 at 11 43 51" src="https://user-images.githubusercontent.com/32645155/99642380-80ba8f80-2a5c-11eb-9928-f1dbbc5037ab.png">

**Comment by sadv1r** [comment]
@aelexor Thanks! I really appreciate your help, if there will be no big problems for a couple of days, I'll move it to stable.

**Comment by aelexor** [comment]
@sadv1r Okay. I can write to you on Monday about the results of using the plugin, as I use it repeatedly every day.

**Comment by artheus** [comment]
Great work! thank you for implementing this so fast!

**Comment by aelexor** [comment]
@sadv1r Hi, I didn't see any problems with the plugin.

**Comment by sadv1r** [comment]
@aelexor Thank you! It was really helpful!
